Metrics collection task
iter8-tools/handler pull request #29
Opened 2021-05-21 20:10 UTC by sriumcp

Resolves iter8-tools/iter8#684

2021-06-01 13:25 UTC, huang195 commented
@sriumcp Is there a design doc to look at besides the PR?

2021-06-01 13:31 UTC, huang195 commented
This looks very fortio specific, but we're calling it `metrics/collect`. Would it make sense to call it more specifically `metrics/fortio` so there could be other `metrics/*` added in later?

2021-06-01 13:46 UTC, kalantar requested changes
some small issues

2021-06-01 13:46 UTC, kalantar commented on lib/metrics/collect.go
> +		return nil, errors.New("library and task need to be 'metrics' and 'collect'")
Use constants `CollectTaskName` and `LibraryName` in both lines.

2021-06-01 13:46 UTC, kalantar commented on lib/metrics/collect.go
> +		t.With.Time = utils.StringPointer("5s")
Use a constant for defaults so that they are easier to find and change.

2021-06-01 13:46 UTC, kalantar commented on lib/metrics/collect.go
> +			t.With.Versions[i].QPS = utils.Float32Pointer(8)
Use a constant for defaults so that they are easier to find and change.

2021-06-01 13:48 UTC, kalantar commented
> This looks very fortio specific, but we're calling it `metrics/collect`. Would it make sense to call it more specifically `metrics/fortio` so there could be other `metrics/*` added in later?

It is fortio specific. However, if our purpose is to provide some build in metrics, I don't think we have to reveal the implementation solution we chose to adopt. In principle, we could change it without changing the name.

If we later choose to add alternatives, we can rename it or alias it at the time.

2021-06-01 13:54 UTC, kalantar commented
I would like to be able to run this manually to try it. I can build a suitable handler image and include in an experiment. However, I need some help to understand what the metrics would look like.

I see some references in the test yaml, but how do define the metrics objects?

2021-06-01 14:04 UTC, sriumcp commented
I agree with @kalantar on Fortio specificity. 

There is nothing Fortio specific about the `metrics/collect` specification / task. This is Iter8's way of surfacing built-in metrics. In particular, end-user documentation for this will not refer to Fortio.

The implementation happens to use Fortio.

2021-06-01 14:19 UTC, sriumcp commented
@kalantar Changes are needed in analytics to complete this feature. FYI. This is merely attacking the handler portion of it.

2021-06-03 13:20 UTC, kalantar approved these changes

2021-06-03 14:14 UTC, huang195 approved these changes

2021-06-03 14:18 UTC, merged