common/bash task
iter8-tools/handler pull request #32
Opened 2021-06-04 21:18 UTC by kalantar

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

Fixes https://github.com/iter8-tools/iter8/issues/733 by introducing an experimental task `common/bash` which improves `common/exec` in two ways:

- removes the need to specify `disableInterpolation` in start tasks; this is determined automatically
- eliminates the need to specify the command (`bin/bash`) and the argument `-c`; these are added immediately.

In addition to these changes, some initial support is added for other tasks including interpolation from the experiment (via the label `.this`) and from a secret. Some refactoring was done to support this.

TBD: if we want to promote this task to be generally available, it needs to be documented in place of `common/exec`.

2021-06-07 13:07 UTC, huang195 submitted a review, later dismissed

2021-06-07 21:41 UTC, sriumcp requested changes

2021-06-07 21:41 UTC, sriumcp commented on lib/notification/notification.go
> +	// add additional tasks here options here
Remove `options here`

2021-06-07 21:41 UTC, sriumcp commented on experiment/experiment.go
> +func GetSecret(namespacedname string) (*corev1.Secret, error) {
What is the purpose of the `GetSecret` function? I do not see it getting used anywhere other than a test? I am also not sure what it has to do with the `bash` task?

2021-06-07 23:39 UTC, kalantar commented on experiment/experiment.go
> +func GetSecret(namespacedname string) (*corev1.Secret, error) {
There is no current purpose, you are right. I had started work already on notification/webhook and wanted to preserve some of the refactoring. I don't need this for bash. But expect to for notification/webhook and for common/http-request (or common/webhook or whatever we call it). I left it in expectation of use. There are test cases for it.

2021-06-08 00:48 UTC, sriumcp approved these changes
lgtm

2021-06-08 10:46 UTC, sriumcp requested changes
In the enforce coverage step of the GH  workflow, we currently check for 74%. Could you please bump this up to 76% since your current code is passing at this level?

2021-06-08 12:32 UTC, huang195 commented on Makefile
> +	@echo "test coverage: $(shell go tool cover -func coverage.out | grep total | awk '{print substr($$3, 1, length($$3)-1)}')"
Can we modify Github workflow so it makes use of the Make targets to avoid duplication. E.g., coverage is done here: https://github.com/iter8-tools/handler/blob/main/.github/workflows/build-and-push.yaml#L51, which is making the same call.

2021-06-08 12:32 UTC, huang195 commented on Makefile
> +	@echo "test coverage: $(shell go tool cover -func coverage.out | grep total | awk '{print substr($$3, 1, length($$3)-1)}')"
This also applies to other Make targets

2021-06-08 13:00 UTC, kalantar commented on Makefile
> +	@echo "test coverage: $(shell go tool cover -func coverage.out | grep total | awk '{print substr($$3, 1, length($$3)-1)}')"
I will create a new issue to address this separately. Issue https://github.com/iter8-tools/iter8/issues/746

2021-06-08 13:02 UTC, huang195 submitted a review, later dismissed

2021-06-08 13:05 UTC, kalantar commented
> In the enforce coverage step of the GH workflow, we currently check for 74%. Could you please bump this up to 76% since your current code is passing at this level?

Done. But I actually think we will struggle to maintain this. Any libraries that use a tool we don't have immediate access to will have to be manually tested. For example, the slack task.

2021-06-08 18:09 UTC, sriumcp approved these changes
lgtm

2021-06-08 18:19 UTC, merged