add common/promote-kubectl
iter8-tools/handler pull request #34
Opened 2021-06-21 16:16 UTC by kalantar

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

Fixes https://github.com/iter8-tools/iter8/issues/798.

2021-06-22 18:03 UTC, kalantar commented
Updated with additional option for `-R` flag for `kubectl apply`

2021-06-24 18:50 UTC, sriumcp approved these changes
lgtm

2021-06-24 19:16 UTC, huang195 commented
@kalantar is there a test yaml file that makes use of `common/kubectl-promote`?

2021-06-24 19:21 UTC, huang195 commented on lib/common/promote_kubectl.go
> +	script := "kubectl --namespace " + *namespace
Where is the verb of `kubectl` being passed here?

2021-06-24 19:23 UTC, kalantar commented
> @kalantar is there a test yaml file that makes use of `common/kubectl-promote`?

There is not. Tests are written manually creating the task from the go object that would have resulted from a yaml file. See TestMakePromoteKubectlTask

2021-06-24 19:25 UTC, huang195 commented
So this allows the handler pod to run `kubectl` command on an arbitrary resource file as input, and it will run as `serviceaccount:iter8-controller`. As any k8s resource could be updated here, this service account could require pretty high level of authorization.

2021-06-24 19:26 UTC, sriumcp reviewed
Agree with @huang195's comment... on verb.

Also without the `apply` verb, I am not sure what the test is actually testing.

2021-06-24 19:27 UTC, sriumcp requested changes
A `Ginkgo` env  test would be useful for this task. See  https://github.com/iter8-tools/handler/blob/main/experiment/experiment_env_test.go for  examples of env tests in this repo.

2021-06-24 19:28 UTC, huang195 commented
> Also without the apply verb, I am not sure what the test is actually testing.

It's not just `apply`. For K8s resources with `generateName` field, you would need to use `create`. Maybe the verb should be passed as an input.

2021-06-24 19:31 UTC, sriumcp commented
> So this allows the handler pod to run kubectl command on an arbitrary resource file as input, and it will run as serviceaccount:iter8-controller. As any k8s resource could be updated here, this service account could require pretty high level of authorization.

serviceaccount:iter8-handler, but the point still applies re: high level of authorization.

Iter8 currently is not multi-tenant. I think this high-level of authorization is ok for this situation. We definitely need to (eventually) answer the multi-tenancy question and design for it.

2021-06-24 19:34 UTC, huang195 commented
I'm reading the issue linked with this PR, so the example given is:

```
      - task: common/promote-kubectl
        with:
          namespace: test
          manifest: "{{ .promotionManifest }}"
```

but is that really that much simpler than?

```
      - task: common/script
        with: |
          kubectl apply -f {{ .promotionManifest }} -n test
```

This is going a great length to get rid of scripts, even one-liners.

2021-06-24 19:35 UTC, huang195 commented on lib/common/common_test.go
> +	assert.Equal(t, "kubectl --namespace default --recursive --filename promote.yaml", bTask.With.Script)
Missing `kubectl` verb here too?

2021-06-24 19:36 UTC, kalantar commented
A gingko test is not suitable f

> A `Ginkgo` env test would be useful for this task. See https://github.com/iter8-tools/handler/blob/main/experiment/experiment_env_test.go for examples of env tests in this repo.

An env test is not suitable for the implementation. They are suitable when calling the go libraries. In this case, `kubectl` is called via a bash task.

2021-06-24 19:43 UTC, sriumcp commented
The promote call itself is a go library call. It happens to use `bash` under the covers as an implementation mechanism.

So yes, `Ginkgo` is suitable.

And it would have caught the lack of verb bug in the current implementation.

2021-06-24 19:47 UTC, kalantar commented
As a bash  command, kubectl needs a valid out of cluster kube config.  As far as I can tell, this is not available for the test environment that can be created for env tests. I did try.

2021-06-28 18:40 UTC, kalantar commented
> So this allows the handler pod to run `kubectl` command on an arbitrary resource file as input, and it will run as `serviceaccount:iter8-controller`. As any k8s resource could be updated here, this service account could require pretty high level of authorization.

Yes. However, we don't make it a requirement that the permission be granted. We have been documenting for each domain the RBAC rules that must be set. Presumably, they will be set for any promote that is defined.

2021-06-28 20:13 UTC, sriumcp approved these changes
lgtm

2021-06-29 20:00 UTC, merged